CREATE TABLE IF NOT EXISTS TODOLIST
(
	id serial PRIMARY KEY,
	title varchar(255) NOT NULL,
	completed boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS TODO_GROUPS
(
	id serial PRIMARY KEY,
	title varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TODO_AND_GROUPS
(
    relation_id serial PRIMARY KEY,
    todo_id INT NOT NULL,
    todo_group_id INT not null,
    FOREIGN KEY(todo_id) REFERENCES TODOLIST(id) ON DELETE CASCADE,
    FOREIGN KEY(todo_group_id) REFERENCES TODO_GROUPS(id)
);

INSERT INTO TODO_GROUPS(TITLE) VALUES('URGENT');
INSERT INTO TODO_GROUPS(TITLE) VALUES('MAYBE TOMORROW');
INSERT INTO TODO_GROUPS(TITLE) VALUES('I DONT KNOW WHEN');

INSERT INTO TODOLIST(TITLE) VALUES('EKB');
INSERT INTO TODO_AND_GROUPS(TODO_ID, TODO_GROUP_ID) VALUES(1, 2);
